'use client'

/**
 * DealImage — wraps next/image with:
 * - Explicit width/height to prevent CLS
 * - Blur placeholder to prevent layout shift during load
 * - Lazy loading (default) or eager for above-fold items
 */

import Image from 'next/image'
import { useState } from 'react'
import clsx from 'clsx'

interface DealImageProps {
  src: string
  alt: string
  width?: number
  height?: number
  priority?: boolean  // true for first ~4 cards (above fold)
  className?: string
}

const PLACEHOLDER_BLUR =
  'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cmVjdCB3aWR0aD0iMTAwJSIgaGVpZ2h0PSIxMDAlIiBmaWxsPSIjMmEyYTNlIi8+PC9zdmc+'

export default function DealImage({
  src,
  alt,
  width = 200,
  height = 200,
  priority = false,
  className,
}: DealImageProps) {
  const [errored, setErrored] = useState(false)

  if (errored || !src) {
    return (
      <div
        className={clsx('bg-surface-raised flex items-center justify-center', className)}
        style={{ width, height }}
        aria-hidden
      >
        <span className="text-4xl">🛒</span>
      </div>
    )
  }

  return (
    <Image
      src={src}
      alt={alt}
      width={width}
      height={height}
      // Prevent CLS: explicit dimensions + aspect-ratio box
      className={clsx('object-contain', className)}
      // Lazy by default; set priority=true for LCP candidates (above fold)
      loading={priority ? 'eager' : 'lazy'}
      priority={priority}
      // Blur placeholder while loading — no blank white flash, no CLS
      placeholder="blur"
      blurDataURL={PLACEHOLDER_BLUR}
      onError={() => setErrored(true)}
      // srcset automatically generated by next/image for responsive sizes
      sizes="(max-width: 640px) 50vw, (max-width: 1200px) 25vw, 200px"
    />
  )
}
